config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # set root to articles index
  root 'articles#index'
  
  # tags to: 'tags#index'

  resources :authors


  
  resources :articles do
    resources :comments #specifies comments as subresource
  end
  resources :tags
    # author sessions: login and logout
    resources :author_sessions, only: [ :new, :create, :destroy ]
    get 'login'  => 'author_sessions#new'
    get 'logout' => 'author_sessions#destroy'
end

# Blogger::Application.routes.draw do
#   resources :articles
# end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :attachements
    has_attached_file :image, styles: { medium: "960x960>", thumb: "100x100>" }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]


    #  article model has to have the tag_list method
    def tag_list
        self.tags.collect do |tag|
          tag.name
        end.join(", ")
    end   
    #  I think this is a setter method for tag_list?
    def tag_list=(tags_string)
      tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
      # possibly an error?
      new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
      self.tags = new_or_found_tags
    end
end

# probably outdated syntax: 
# class Article < ActiveRecord::Base
#     has_many :comments
# end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # include modules here:
    include ArticlesHelper

    #ArticlesController methods
    def index
        @articles = Article.all
    end
    def show
        @article = Article.find(params[:id])


        # creating the blank comment object:
        @comment = Comment.new
        #  wrong example: 
        # @comment = @article.comments.new 
        
        @comment.article_id = @article.id


    end
    def new
        @article = Article.new
    end
    
    def create
    # passing in the whole hash for the article will throw error:
    # ======================================
        # @article = Article.new(params[:article])   <--------------- this is a security risk, hence will throw error
        @article = Article.new(article_params) # <------------ articles_params is a helper method defined in articles_helper.rb
        # rmb to save and redirect
        @article.save
        flash.notice = "A new article:'#{@article.title}' has been created!"

        redirect_to article_path(@article)


    # an attempt at one-by-one getting out the hash, which might be unnecessary, as we could just pass in the whole hash:
    # =====================================================================================================================
    # @article = Article.new(
    #     title: params[:article][:title],
    #     body: params[:article][:body])
    #   @article.save
    #   redirect_to article_path(@article)

    #  this way not recommended because the instance variables are known to the controller, and we don't want the controller to know too much:
    # ===============================================================================================================
    #     @article = Article.new
    #     @article.title = params[:article][:title]
    #     @article.body = params[:article][:body]
    #     @article.save

    #     redirect_to article_path(@article)
    end

    def destroy 
        article = Article.find(params[:id])
        string = article.title
        article.destroy
        flash.notice = "Article '#{string}' has been Destroyed!!"
        redirect_to articles_path(index)
    end


    # edit action finds the object (article) and displays the form
    def edit 
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        # add in a flash to notify user:
        flash.notice = "Article '#{@article.title}' Updated!"

        # do the necessary redirection after the action
        redirect_to article_path(@article)
    end

    
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
      params.require(:article).permit(:title, :body, :tag_list, :image)
      end
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>

</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <%# Text input for Title %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <%# Text input for Body %>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <%# Tagging interface %>
  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
  </p>
  <%# File uploading: %>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Insert pictorial evidence" %><br />
    <%= f.file_field :image %>
  </p>
  
  
  <%#  submit button!!! %>
  <p>
    <%= f.submit %>
  </p>


<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: "article_title", id: "article_#{article.id}"=%>
      <%# article.title is the text that the link says. The article_path(article) is the route helper %>
      <%# when template is rendered, it outputs HTML like a normal anchor tag %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Article", new_article_path, class: "new_article"%>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%# placing the image for the article %>
<%= image_tag @article.image.url(:medium) %>

<p><%= @article.body %></p>


<%# embedding partial comments form: %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<% if logged_in? %>

  <%= link_to "delete", article_path(@article), method: :delete , data: {confirm: "you sure you want to delete the post bruh??"}%>
  <%= link_to "edit", edit_article_path(@article) %>

<% end %>






<h3>Comments (<%= @article.comments.size %>)</h3>


<%= render partial: 'articles/comment', collection: @article.comments %>