config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # set root to articles index
  root 'articles#index'
  
  # tags to: 'tags#index'

  resources :authors


  
  resources :articles do
    resources :comments #specifies comments as subresource
  end
  resources :tags
    # author sessions: login and logout
    resources :author_sessions, only: [ :new, :create, :destroy ]
    get 'login'  => 'author_sessions#new'
    get 'logout' => 'author_sessions#destroy'
end

# Blogger::Application.routes.draw do
#   resources :articles
# end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :articles, through: :taggings

    # optional?
    def to_s
        name
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    # before_filter :require_login, only: [:destroy]
  def index 
      @tags = Tag.all 
  end


    def show
        @tag = Tag.find(params[:id])
    end
    def destroy 
        tag = Tag.find(params[:id])
        string = tag.name
        tag.destroy
        flash.notice = "Tag '#{string}' has been Destroyed!!"
        redirect_to tags_path(index)
    end
    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag), class: "tag_name", id: "tag_#{tag.id}" =%>
    </li>
  <% end %>
</ul>
<%# <%= link_to "Create a New Tag", new_tag_path, class: "new_tag"%> 

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
<%= link_to "delete", tag_path(@tag), method: :delete , data: {confirm: "you sure you want to delete the tag bruh??"}%>

</ul>